name: build
on:
  workflow_call:
    inputs:
      workspace:
        type: string
        default: jazzy-develop
  workflow_dispatch:
    inputs:
      workspace:
        type: string
        default: jazzy-develop
env:
  REGISTRY: ghcr.io
  ORG_NAME: cubesys-gmbh
  IMAGE_NAME: ros_v2x_apps
jobs:
  build:
    runs-on: ubuntu-latest
    name: build ros_v2x_apps image
    permissions:
      contents: read
      packages: write
    steps:
    - name: check out repo
      uses: actions/checkout@v4
    - name: set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: log on to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: extract metadata for image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ inputs.workspace}},enable=${{ github.ref == 'refs/heads/master' }}
          type=sha,prefix=${{ inputs.workspace }}-git+
    - name: build and push image
      uses: docker/build-push-action@v6
      id: build
      with:
        platforms: linux/amd64, linux/arm64
        push: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: WORKSPACE_VERSION=${{ inputs.workspace }}
